const CATEGORIES = [
    "Hyper-Real Illusions",
    "Pocket Worlds",
    "Reverse Cause & Effect",
    "Everyday Portals",
    "Reality Errors",
    "Micro Mundane Rebels",
    "Time Sneaks",
    "Nature Reboots",
    "Emotions as Errors",
    "Micro Dreams",
    "Parallel Me",
    "AI Paradoxes",
    "Cute → Creepy → Cute",
    "Instant Evolution",
    "Object Existential Crisis",
    "Impossible Lifestyle Hacks",
    "Emotion Metaphors",
    "Data Ghosts",
    "Pocket Time Machines",
    "Dream Becomes News",
    "Everyday Deities",
    "Reflections in Reverse",
    "Digital Wildlife",
    "Forgotten Futures",
    "Urban Myths 2.0",
    "Silent Signals",
    "Quantum Routines",
    "Human Software Updates",
    "Dream Shortcuts",
    "Reality Audits"
];

const VIRAL_RULES = {
    shock: { weight: 25, desc: "Instant hook/twist" },
    visual: { weight: 20, desc: "Ultra-visual clarity" },
    weird: { weight: 20, desc: "Relatable but weird" },
    loop: { weight: 20, desc: "Loopable/replayable" },
    emotion: { weight: 15, desc: "Emotional hook + curiosity" }
};